name: charity_collection_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  twilio_flutter:


  provider: ^6.0.5
  google_fonts:
  # Firebase (MATCHED VERSIONS)
  #firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.1.0
  firebase_core: ^3.6.0
  cloud_functions: ^5.6.2
  pdf: ^3.10.1
  open_filex: ^4.4.0
  path_provider: ^2.1.2
  excel: ^4.0.3
  intl_phone_number_input: ^0.7.0+2
  share_plus: ^7.2.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  mobile_scanner: ^5.0.0

  permission_handler: ^11.3.1
  printing: ^5.11.0
  intl: ^0.18.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/nagina.jpeg"
  min_sdk_android: 21

